version: "3.1"
services:
  #PHP Service
  app-dmz:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:7.4-fpm-alpine
    container_name: app-dmz
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app-dmz
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver-dmz:
    image: nginx:alpine
    container_name: webserver-dmz
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
    networks:
      - app-network

  #MySQL Service
  database-dmz:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: database-dmz
    restart: always
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: dmz
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  adminer-dmz:
    container_name: adminer-dmz
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network


#Docker Networks
networks:
  app-network:
    driver: bridge
#volumes
volumes:
  dbdata:
    driver: local
