ALTER SEQUENCE types_id_seq RESTART WITH 3;
ALTER SEQUENCE users_id_seq RESTART WITH 2;
ALTER SEQUENCE transfers_id_seq RESTART WITH 27;
ALTER SEQUENCE offerings_id_seq RESTART WITH 53;
ALTER SEQUENCE tithes_id_seq RESTART WITH 76;
